framingham <- read.csv("framingham.csv")
str(framingham)
install.packages("caTools")
library(caTools)
set.seed(1000)
split <- sample.split(framingham$TenYearCHD, 0.65)
ftrain <- subset(framingham,split == TRUE)
ftest <- subset(framingham,split == FALSE)
flog <- glm(TenYearCHD~.,data = ftrain, family = "binomial")
summary(flog)
predicttest <- predict(flog,newdata=ftest,type = "response")
table(ftest$TenYearCHD,predicttest > 0.5)
install.packages("ROCR")
library(ROCR)
rocrpred <- prediction(predicttest,ftest$TenYearCHD)
as.numeric(performance(rocrpred,"auc")@"y.values")
