data(state)
statedata = cbind(data.frame(state.x77), state.abb, state.area, state.center,  state.division, state.name, state.region)
str(statedata)
library(dplyr)
plot(statedata$x,statedata$y)
tapply(statedata$HS.Grad,statedata$state.region,mean)
boxplot(Murder~state.region,data=statedata,main="Murder by Region",
        xlab="Region", ylab="Murders",col="orange")
filter(statedata,state.region=="Northeast")
life.exp1 <- lm(Life.Exp~Population+Income+Illiteracy+Murder+HS.Grad+Frost+Area,data=statedata)
summary(life.exp1)
plot(statedata$Income,statedata$Life.Exp)
life.exp2 <- lm(Life.Exp~Population+Income+Illiteracy+Murder+HS.Grad+Frost,data=statedata)
summary(life.exp2)
life.exp2 <- lm(Life.Exp~Population+Income+Murder+HS.Grad+Frost,data=statedata)
summary(life.exp2)
life.exp2 <- lm(Life.Exp~Population+Murder+HS.Grad+Frost,data=statedata)
summary(life.exp2)
sort(predict(life.exp2))
statedata[which.min(statedata$Life.Exp),]
