polling <- read.csv("PollingData.csv")
str(polling)
table(polling$Year)
summary(polling)
install.packages("mice")
library(mice)
library(dplyr)
simplenames <- colnames(polling)[1:6]
simple <- select(polling,simplenames)
set.seed(144)
imputed <- complete(mice(simple))
summary(imputed)
polling[c("Rasmussen","SurveyUSA")] = imputed[c("Rasmussen","SurveyUSA")]
summary(polling)
train <- filter(polling,Year < 2012)
test <- filter(polling,Year == 2012)
table(train$Republican)
table(train$Republican,sign(train$Rasmussen))
cornames <- colnames(polling)[2:7]
cor(train[cornames])
mod1 <- glm(Republican~PropR,data = train, family = "binomial")
summary(mod1)
pred1 <- predict(mod1, type="response")
table(train$Republican,pred1>0.5)
mod2 <- glm(Republican~SurveyUSA+DiffCount,data = train, family = "binomial")
summary(mod2)
pred2 <- predict(mod2,type="response")
table(train$Republican,pred2>0.5)
table(test$Republican,sign(test$Rasmussen))
39/45
pred3 <- predict(mod2,newdata=test,type="response")
table(test$Republican,pred3>0.5)
filter(test,pred3>0.5 & test$Republican == 0)
