library(dplyr)
library(ROCR)
library(caTools)
parole <- read.csv("parole.csv")
str(parole)
summary(parole)
table(parole$violator)
parole$state <- as.factor(parole$state)
parole$crime <- as.factor(parole$crime)
summary(parole)
set.seed(144)
split = sample.split(parole$violator, SplitRatio = 0.7)
train = subset(parole, split == TRUE)
test = subset(parole, split == FALSE)
model1 <- glm(violator~.,data = train, family=binomial)
summary(model1)
parolee <- c(1,1,1,50,0,0,0,3,12,0,1,0,0)
coeff <- as.data.frame(model1[1])
sum(parolee*coeff)
exp(sum(parolee*coeff))
pred1 <- predict(model1,newdata=test,type = "response")
max(pred1)
pred1table <- table(test$violator,pred1>0.5)
sens <- pred1table[2,2]/sum(pred1table[2,])
spec <- pred1table[1,1]/sum(pred1table[1,])
accu <- (pred1table[1,1]+pred1table[2,2])/sum(pred1table)
sens
spec
accu
prop.table(table(test$violator))
rocrpred <- prediction(pred1,test$violator)
performance(rocrpred,"auc")@"y.values"
