library(ggplot2)
library("RColorBrewer")
boston <- read.csv("boston.csv")
str(boston)
boston$CHAS <- factor(boston$CHAS)
tractMIT <- subset(boston, TRACT == 3531)
p1 <- ggplot(boston,aes(LON, LAT))+ geom_point()
p2 <- p1 + geom_point(data = tractMIT,aes(LON, LAT),color = "orange", size = 3, shape = 17)
p2
summary(boston$NOX)
qplot(boston$NOX)
poltract <- subset(boston, NOX >= 0.55)
p2 +geom_point(data = poltract, aes(LON, LAT),color = "green")
qplot(boston$MEDV)
p1 + geom_point(aes(color = MEDV))
p2 <- p1 + geom_point(data = subset(boston, MEDV>=21.2),color = "red")
plot(boston$LAT,boston$MEDV)
plot(boston$LON,boston$MEDV)
latlonlm <- lm(MEDV~LAT+LON,data=boston)
summary(latlonlm)
latlonpredval <- latlonlm$fitted.values
p2 + geom_point(data = subset(boston, latlonpredval > 21.2),color = "blue", shape = "$")
library(rpart)
library(rpart.plot)
latlontree <- rpart(MEDV~LAT+LON, data = boston)
prp(latlontree)
fittedvalues <- predict(latlontree)
p2 + geom_point(data = subset(boston,fittedvalues > 21.2),color = "blue", shape = "$")
latlontree <- rpart(MEDV~LAT+LON, data = boston, minbucket = 50)
plot(latlontree)
text(latlontree)
library(caTools)
set.seed(123)
split <- sample.split(boston$MEDV, SplitRatio = 0.7)
train <- subset(boston,split == TRUE)
test <- subset(boston,split == FALSE)
linreg <- lm(MEDV~LAT+LON+CRIM+ZN+INDUS+CHAS+NOX+RM+AGE+DIS+RAD+TAX+PTRATIO,data=train)
summary(linreg)
linreg.pred <- predict(linreg,newdata=test)
linreg.sse <- sum((linreg.pred - test$MEDV)^2)
linreg.sse
tree <- rpart(MEDV~LAT+LON+CRIM+ZN+INDUS+CHAS+NOX+RM+AGE+DIS+RAD+TAX+PTRATIO,data=train)
prp(tree)
tree.pred <- predict(tree,newdata=test)
tree.sse <- sum((tree.pred - test$MEDV)^2)
tree.sse
library(caret)
library(e1071)
tr.control <- trainControl(method="cv",number=10)
cp.grid <- expand.grid(.cp = (0:10)*0.001)
tr <- train(MEDV~LAT+LON+CRIM+ZN+INDUS+CHAS+NOX+RM+AGE+DIS+RAD+TAX+PTRATIO, 
            data = train, method = "rpart", trControl = tr.control, tuneGrid = cp.grid)
tr
best.tree <- tr$finalModel
prp(best.tree)
best.tree.pred <- predict(best.tree, newdata= test)
